# Cloud Build pipeline for BulnaAI (Next.js)
# References:
# - https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# - https://cloud.google.com/sql/docs/postgres/connect-run#terraform (Cloud SQL deploy flags)

options:
    logging: CLOUD_LOGGING_ONLY
    machineType: E2_HIGHCPU_8

tags:
    - creative-flow-studio
    - nextjs

substitutions:
    _REGION: asia-northeast1
    _PROJECT_ID: dataanalyticsclinic
    _REPO: creative-flow-studio
    _IMAGE_NAME: app
    _SERVICE_NAME: creative-flow-studio-dev
    _CLOUD_SQL_INSTANCE: dataanalyticsclinic:asia-northeast1:creative-flow-studio-sql
    _VPC_CONNECTOR: projects/dataanalyticsclinic/locations/asia-northeast1/connectors/dev-serverless-connector
    _SERVICE_ACCOUNT: cloud-run-runtime@dataanalyticsclinic.iam.gserviceaccount.com
    _NEXT_PUBLIC_APP_URL: 'SET_IN_TRIGGER'
    _NEXT_PUBLIC_SUPABASE_URL: 'SET_IN_TRIGGER'

serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/cloud-build-runner@dataanalyticsclinic.iam.gserviceaccount.com

availableSecrets:
    secretManager:
        # DATABASE_URL is included for migration step only, not for Next.js build
        # Use explicit version number to avoid DESTROYED version issues
        # Cloud Build will automatically use the latest enabled version
        - versionName: projects/${_PROJECT_ID}/secrets/database-url/versions/latest
          env: DATABASE_URL
        - versionName: projects/${_PROJECT_ID}/secrets/nextauth-secret/versions/latest
          env: NEXTAUTH_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-id/versions/latest
          env: GOOGLE_CLIENT_ID
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-secret/versions/latest
          env: GOOGLE_CLIENT_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-service-role/versions/latest
          env: SUPABASE_SERVICE_ROLE_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-secret-key/versions/latest
          env: STRIPE_SECRET_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-webhook-secret/versions/latest
          env: STRIPE_WEBHOOK_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/gemini-api-key/versions/latest
          env: GEMINI_API_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-anon-key/versions/latest
          env: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-publishable-key/versions/latest
          env: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

steps:
    - id: 'Install dependencies'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: bash
      args:
          - '-c'
          - |
              set -euo pipefail
              echo "Cloud Build Node version: $(node --version)"
              npm ci

    - id: 'Generate Prisma client'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npx
      args: ['prisma', 'generate']

    - id: 'Check Cloud SQL instance exists'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              set -euo pipefail

              echo "🔍 Cloud SQLインスタンスの存在を確認しています..."
              INSTANCE_NAME=$(echo "${_CLOUD_SQL_INSTANCE}" | cut -d':' -f3)
              PROJECT_ID=$(echo "${_CLOUD_SQL_INSTANCE}" | cut -d':' -f1)

              if gcloud sql instances describe "$$INSTANCE_NAME" --project="$$PROJECT_ID" > /dev/null 2>&1; then
                  echo "✅ Cloud SQLインスタンスが見つかりました: $$INSTANCE_NAME"
                  echo "true" > /workspace/.cloud_sql_exists
              else
                  echo "⚠️  Cloud SQLインスタンスが見つかりません: $$INSTANCE_NAME"
                  echo "   マイグレーションステップをスキップします。"
                  echo "   Terraformでインフラを先にデプロイしてください。"
                  echo "false" > /workspace/.cloud_sql_exists
              fi
      waitFor: ['Generate Prisma client']

    - id: 'Get Cloud SQL public IP'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              set -euo pipefail

              # Cloud SQLインスタンスの存在確認
              if [ -f /workspace/.cloud_sql_exists ] && [ "$(cat /workspace/.cloud_sql_exists)" = "false" ]; then
                  echo "⏭️  Cloud SQLインスタンスが存在しないため、スキップします。"
                  exit 0
              fi

              echo "🔍 Cloud SQLのパブリックIPを取得しています..."
              INSTANCE_NAME=$(echo "${_CLOUD_SQL_INSTANCE}" | cut -d':' -f3)
              PROJECT_ID=$(echo "${_CLOUD_SQL_INSTANCE}" | cut -d':' -f1)

              PUBLIC_IP=$(gcloud sql instances describe "$$INSTANCE_NAME" \
                  --project="$$PROJECT_ID" \
                  --format="value(ipAddresses[0].ipAddress)" 2>/dev/null || echo "")

              if [ -z "$$PUBLIC_IP" ]; then
                  echo "⚠️  パブリックIPが見つかりません。Terraformでipv4_enabled=trueを設定してください。"
                  echo "false" > /workspace/.cloud_sql_has_public_ip
              else
                  echo "✅ パブリックIP: $$PUBLIC_IP"
                  echo "$$PUBLIC_IP" > /workspace/.cloud_sql_public_ip
                  echo "true" > /workspace/.cloud_sql_has_public_ip
              fi
      waitFor: ['Check Cloud SQL instance exists']

    - id: 'Apply database migrations'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              set -euo pipefail

              # DATABASE_URLを取得（Secret Managerから直接取得してDESTROYEDバージョンを回避）
              echo "🔑 データベース接続情報を取得しています..."
              if [ -z "$$DATABASE_URL" ]; then
                  echo "❌ DATABASE_URL環境変数が設定されていません"
                  exit 1
              fi

              # Cloud SQLインスタンスの存在確認
              if [ -f /workspace/.cloud_sql_exists ] && [ "$(cat /workspace/.cloud_sql_exists)" = "false" ]; then
                  echo "⏭️  Cloud SQLインスタンスが存在しないため、マイグレーションをスキップします。"
                  exit 0
              fi

              # パブリックIPの確認
              if [ -f /workspace/.cloud_sql_has_public_ip ] && [ "$(cat /workspace/.cloud_sql_has_public_ip)" = "false" ]; then
                  echo "⚠️  Cloud SQLにパブリックIPがないため、マイグレーションをスキップします。"
                  echo "   Cloud Runデプロイ後、Unix socket経由でマイグレーションを実行してください。"
                  exit 0
              fi

              PUBLIC_IP=$(cat /workspace/.cloud_sql_public_ip)
              echo "🔗 Cloud SQL パブリックIP経由で接続します: $$PUBLIC_IP"

              # DATABASE_URLからユーザー名、パスワード、DB名を抽出して新しいURLを構築
              # 元の形式: postgresql://user:pass@/db?host=/cloudsql/...
              DB_URL="$$DATABASE_URL"

              # ユーザー名を抽出
              DB_USER=$(echo "$$DB_URL" | sed -n 's|postgresql://\([^:]*\):.*|\1|p')
              # パスワードを抽出（@/より前の:以降）
              DB_PASS=$(echo "$$DB_URL" | sed -n 's|postgresql://[^:]*:\([^@]*\)@.*|\1|p')
              # DB名を抽出（@/と?の間）
              DB_NAME=$(echo "$$DB_URL" | sed -n 's|.*@/\([^?]*\)?.*|\1|p')

              echo "  ユーザー: $$DB_USER"
              echo "  DB名: $$DB_NAME"

              # パブリックIP経由のDATABASE_URLを構築（SSL必須）
              export DATABASE_URL="postgresql://$$DB_USER:$$DB_PASS@$$PUBLIC_IP:5432/$$DB_NAME?sslmode=require"
              echo "  接続先: postgresql://$$DB_USER:****@$$PUBLIC_IP:5432/$$DB_NAME?sslmode=require"

              # Prismaマイグレーションを実行
              echo "🔄 データベースマイグレーションを適用しています..."

              # 接続エラー用のリトライ設定
              MAX_RETRIES=5
              RETRY_COUNT=0

              set +e
              while [ $$RETRY_COUNT -lt $$MAX_RETRIES ]; do
                  ERROR_OUTPUT=$(npx prisma migrate deploy 2>&1)
                  EXIT_CODE=$$?

                  if [ $$EXIT_CODE -eq 0 ]; then
                      echo "✅ マイグレーションが正常に完了しました"
                      exit 0
                  fi

                  # 接続エラーの場合はリトライ
                  if echo "$$ERROR_OUTPUT" | grep -qE "(P1001|P1002|ECONNREFUSED|timeout)"; then
                      RETRY_COUNT=$$((RETRY_COUNT + 1))
                      echo "  接続エラー。試行 $$RETRY_COUNT/$$MAX_RETRIES..."
                      sleep 3
                      continue
                  fi

                  # P3005: 既存スキーマがある場合はbaselineを設定
                  if echo "$$ERROR_OUTPUT" | grep -q "P3005"; then
                      echo "⚠️  既存のスキーマが存在します。baselineを設定します..."
                      FIRST_MIGRATION=$(ls -1 prisma/migrations 2>/dev/null | grep -v "^_" | head -1)
                      if [ -n "$$FIRST_MIGRATION" ]; then
                          npx prisma migrate resolve --applied "$$FIRST_MIGRATION" 2>&1 || true
                          continue
                      fi
                  fi

                  # その他のエラー
                  echo "❌ マイグレーションエラー:"
                  echo "$$ERROR_OUTPUT"
                  exit 1
              done
              set -e

              echo "❌ マイグレーションに失敗しました（$$MAX_RETRIES回試行）"
              exit 1
      secretEnv:
          - DATABASE_URL
      waitFor: ['Get Cloud SQL public IP']

    - id: 'Build Next.js app'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npm
      args: ['run', 'build']
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
          # NOTE: DATABASE_URL is NOT set during build - it's only set at runtime in Cloud Run
          # This prevents Next.js from hardcoding the DATABASE_URL during build
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - SUPABASE_SERVICE_ROLE_KEY
          - STRIPE_SECRET_KEY
          - STRIPE_WEBHOOK_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

    - id: 'Build container image'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      args:
          - '-c'
          - |
              docker build \
                --build-arg NEXT_PUBLIC_APP_URL="${_NEXT_PUBLIC_APP_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_URL="${_NEXT_PUBLIC_SUPABASE_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
                --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" \
                --build-arg GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID \
                --build-arg GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET \
                --build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET \
                --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY \
                -t asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA} \
                -f Dockerfile \
                .

    - id: 'Push container image'
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'

    - id: 'Deploy to Cloud Run'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - '${_SERVICE_NAME}'
          - '--project=${_PROJECT_ID}'
          - '--region=${_REGION}'
          - '--image=asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
          - '--service-account=${_SERVICE_ACCOUNT}'
          - '--platform=managed'
          - '--vpc-connector=${_VPC_CONNECTOR}'
          - '--set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
          - '--ingress=all'
          - '--allow-unauthenticated'
          - '--quiet'

images:
    - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
