# Cloud Build pipeline for Creative Flow Studio (Next.js)
# References:
# - https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# - https://cloud.google.com/sql/docs/postgres/connect-run#terraform (Cloud SQL deploy flags)

options:
    logging: CLOUD_LOGGING_ONLY
    machineType: E2_HIGHCPU_8

tags:
    - creative-flow-studio
    - nextjs

substitutions:
    _REGION: asia-northeast1
    _PROJECT_ID: dataanalyticsclinic
    _REPO: creative-flow-studio
    _IMAGE_NAME: app
    _SERVICE_NAME: creative-flow-studio-dev
    _CLOUD_SQL_INSTANCE: dataanalyticsclinic:asia-northeast1:creative-flow-studio-sql
    _VPC_CONNECTOR: projects/dataanalyticsclinic/locations/asia-northeast1/connectors/dev-serverless-connector
    _SERVICE_ACCOUNT: cloud-run-runtime@dataanalyticsclinic.iam.gserviceaccount.com
    _NEXT_PUBLIC_APP_URL: 'SET_IN_TRIGGER'
    _NEXT_PUBLIC_SUPABASE_URL: 'SET_IN_TRIGGER'

serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/cloud-build-runner@dataanalyticsclinic.iam.gserviceaccount.com

availableSecrets:
    secretManager:
        # DATABASE_URL is included for migration step only, not for Next.js build
        - versionName: projects/${_PROJECT_ID}/secrets/database-url/versions/latest
          env: DATABASE_URL
        - versionName: projects/${_PROJECT_ID}/secrets/nextauth-secret/versions/latest
          env: NEXTAUTH_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-id/versions/latest
          env: GOOGLE_CLIENT_ID
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-secret/versions/latest
          env: GOOGLE_CLIENT_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-service-role/versions/latest
          env: SUPABASE_SERVICE_ROLE_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-secret-key/versions/latest
          env: STRIPE_SECRET_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-webhook-secret/versions/latest
          env: STRIPE_WEBHOOK_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/gemini-api-key/versions/latest
          env: GEMINI_API_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-anon-key/versions/latest
          env: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-publishable-key/versions/latest
          env: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

steps:
    - id: 'Install dependencies'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: bash
      args:
          - '-c'
          - |
              set -euo pipefail
              echo "Cloud Build Node version: $(node --version)"
              npm ci

    - id: 'Generate Prisma client'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npx
      args: ['prisma', 'generate']

    - id: 'Apply database migrations'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              set -euo pipefail
              
              # Cloud SQL Proxy v2をダウンロード
              echo "📥 Cloud SQL Proxy v2をダウンロードしています..."
              curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.19.0/cloud-sql-proxy.linux.amd64
              chmod +x cloud-sql-proxy
              
              # Cloud SQL Proxyをバックグラウンドで起動
              echo "🚀 Cloud SQL Proxyを起動しています..."
              echo "   インスタンス: ${_CLOUD_SQL_INSTANCE}"
              echo "   パブリックIP接続を使用します"
              ./cloud-sql-proxy ${_CLOUD_SQL_INSTANCE} --port=5432 --address=127.0.0.1 > /tmp/cloud-sql-proxy.log 2>&1 &
              PROXY_PID=$!
              
              # Proxyが起動するまで待機（最大30秒）
              echo "⏳ Cloud SQL Proxyの起動を待機しています..."
              for i in {1..30}; do
                  if ps -p $$PROXY_PID > /dev/null 2>&1; then
                      # ポート5432がリッスンしているか確認（timeoutコマンドを使用）
                      if timeout 1 bash -c "echo > /dev/tcp/127.0.0.1/5432" 2>/dev/null; then
                          echo "✅ Cloud SQL Proxyが起動しました (PID: $$PROXY_PID, 試行: $$i/30)"
                          break
                      fi
                  else
                      echo "❌ Cloud SQL Proxyの起動に失敗しました"
                      cat /tmp/cloud-sql-proxy.log
                      exit 1
                  fi
                  if [ $$i -eq 30 ]; then
                      echo "❌ Cloud SQL Proxyの起動がタイムアウトしました"
                      cat /tmp/cloud-sql-proxy.log
                      exit 1
                  fi
                  sleep 1
              done
              
              # DATABASE_URLを取得して、localhost経由に変換
              echo "🔑 データベース接続情報を取得しています..."
              DB_URL=$$DATABASE_URL
              echo "  元のDATABASE_URL: $$DB_URL"
              
              # Unix socket形式からTCP形式に変換
              # postgresql://user:pass@/db?host=/cloudsql/... -> postgresql://user:pass@127.0.0.1:5432/db
              DB_URL_LOCAL=$(echo "$$DB_URL" | sed 's|host=/cloudsql/[^?]*||' | sed 's|@/|@127.0.0.1:5432/|')
              echo "  変換後のDATABASE_URL: $$DB_URL_LOCAL"
              
              # Prismaマイグレーションを実行（接続確認も兼ねる）
              echo "🔄 データベースマイグレーションを適用しています..."
              export DATABASE_URL="$$DB_URL_LOCAL"
              
              # 接続エラー用のリトライ設定
              MAX_CONNECTION_RETRIES=10
              CONNECTION_RETRY_COUNT=0
              
              # マイグレーションエラー用のリトライ設定（無限ループ防止）
              MAX_MIGRATION_RETRIES=3
              MIGRATION_RETRY_COUNT=0
              
              # set -eを一時的に無効化してエラーハンドリングを行う
              set +e
              
              # 接続エラーのリトライループ
              while [ $$CONNECTION_RETRY_COUNT -lt $$MAX_CONNECTION_RETRIES ]; do
                  # Prisma migrate deployを実行
                  ERROR_OUTPUT=$(npx prisma migrate deploy 2>&1)
                  EXIT_CODE=$$?
                  
                  if [ $$EXIT_CODE -eq 0 ]; then
                      echo "✅ マイグレーションが正常に完了しました"
                      set -e
                      break
                  fi
                  
                  # 接続エラー（P1001）の場合はリトライ
                  if echo "$$ERROR_OUTPUT" | grep -q "P1001"; then
                      CONNECTION_RETRY_COUNT=$$((CONNECTION_RETRY_COUNT + 1))
                      echo "  接続エラー。試行 $$CONNECTION_RETRY_COUNT/$$MAX_CONNECTION_RETRIES..."
                      if [ $$((CONNECTION_RETRY_COUNT % 5)) -eq 0 ]; then
                          echo "  エラー詳細: $$ERROR_OUTPUT"
                          echo "  Cloud SQL Proxyログ（最新10行）:"
                          tail -n 10 /tmp/cloud-sql-proxy.log || true
                      fi
                      sleep 2
                      continue
                  fi
                  
                  # 接続エラー以外の場合は、マイグレーションエラーの処理に移る
                  break
              done
              
              # 接続リトライが上限に達した場合
              if [ $$CONNECTION_RETRY_COUNT -eq $$MAX_CONNECTION_RETRIES ]; then
                  set -e
                  echo "❌ データベース接続の確立に失敗しました（$$MAX_CONNECTION_RETRIES回試行）"
                  echo "Cloud SQL Proxyログ:"
                  cat /tmp/cloud-sql-proxy.log
                  exit 1
              fi
              
              # マイグレーションエラーの処理（無限ループ防止のため最大3回まで）
              if [ $$EXIT_CODE -ne 0 ]; then
                  while [ $$MIGRATION_RETRY_COUNT -lt $$MAX_MIGRATION_RETRIES ]; do
                      # スキーマが空でないエラー（P3005）の場合はbaselineを設定
                      if echo "$$ERROR_OUTPUT" | grep -q "P3005"; then
                          echo "⚠️  データベースに既存のスキーマが存在します。baselineを設定します..."
                          MIGRATIONS=$(ls -1 prisma/migrations 2>/dev/null | grep -v "^_" | head -1)
                          if [ -n "$$MIGRATIONS" ]; then
                              echo "  最初のマイグレーションをbaselineとして設定: $$MIGRATIONS"
                              npx prisma migrate resolve --applied "$$MIGRATIONS" 2>&1 || true
                              MIGRATION_RETRY_COUNT=$$((MIGRATION_RETRY_COUNT + 1))
                              # 再度migrate deployを実行
                              ERROR_OUTPUT=$(npx prisma migrate deploy 2>&1)
                              EXIT_CODE=$$?
                              if [ $$EXIT_CODE -eq 0 ]; then
                                  echo "✅ マイグレーションが正常に完了しました"
                                  set -e
                                  break
                              fi
                              continue
                          else
                              set -e
                              echo "❌ マイグレーションファイルが見つかりません"
                              echo "$$ERROR_OUTPUT"
                              exit 1
                          fi
                      # マイグレーションファイルが見つからないエラー（P3017）の場合は、存在しないマイグレーションをbaselineとして設定
                      elif echo "$$ERROR_OUTPUT" | grep -q "P3017"; then
                          echo "⚠️  データベースに存在するが、ソースコードに存在しないマイグレーションが見つかりました。"
                          MISSING_MIGRATION=$(echo "$$ERROR_OUTPUT" | grep -oE "migration [0-9a-zA-Z_]+" | awk '{print $2}' | head -1)
                          if [ -n "$$MISSING_MIGRATION" ]; then
                              echo "  存在しないマイグレーションをbaselineとして設定: $$MISSING_MIGRATION"
                              npx prisma migrate resolve --applied "$$MISSING_MIGRATION" 2>&1 || true
                              MIGRATION_RETRY_COUNT=$$((MIGRATION_RETRY_COUNT + 1))
                              # 再度migrate deployを実行
                              ERROR_OUTPUT=$(npx prisma migrate deploy 2>&1)
                              EXIT_CODE=$$?
                              if [ $$EXIT_CODE -eq 0 ]; then
                                  echo "✅ マイグレーションが正常に完了しました"
                                  set -e
                                  break
                              fi
                              continue
                          else
                              set -e
                              echo "❌ マイグレーション名を抽出できませんでした"
                              echo "$$ERROR_OUTPUT"
                              exit 1
                          fi
                      else
                          # その他のエラー
                          set -e
                          echo "❌ マイグレーションエラー:"
                          echo "$$ERROR_OUTPUT"
                          echo ""
                          echo "Cloud SQL Proxyログ:"
                          cat /tmp/cloud-sql-proxy.log
                          exit 1
                      fi
                  done
                  
                  # マイグレーションリトライが上限に達した場合
                  if [ $$MIGRATION_RETRY_COUNT -eq $$MAX_MIGRATION_RETRIES ] && [ $$EXIT_CODE -ne 0 ]; then
                      set -e
                      echo "❌ マイグレーションの適用に失敗しました（$$MAX_MIGRATION_RETRIES回試行）"
                      echo "エラー詳細: $$ERROR_OUTPUT"
                      echo "Cloud SQL Proxyログ:"
                      cat /tmp/cloud-sql-proxy.log
                      exit 1
                  fi
              fi
              
              set -e
              
              # Proxyを停止
              echo "🛑 Cloud SQL Proxyを停止しています..."
              kill $$PROXY_PID 2>/dev/null || true
              wait $$PROXY_PID 2>/dev/null || true
              
              echo "✅ マイグレーションが正常に完了しました"
      secretEnv:
          - DATABASE_URL
      waitFor: ['Generate Prisma client']

    - id: 'Build Next.js app'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npm
      args: ['run', 'build']
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
          # NOTE: DATABASE_URL is NOT set during build - it's only set at runtime in Cloud Run
          # This prevents Next.js from hardcoding the DATABASE_URL during build
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - SUPABASE_SERVICE_ROLE_KEY
          - STRIPE_SECRET_KEY
          - STRIPE_WEBHOOK_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

    - id: 'Build container image'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      args:
          - '-c'
          - |
              docker build \
                --build-arg NEXT_PUBLIC_APP_URL="${_NEXT_PUBLIC_APP_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_URL="${_NEXT_PUBLIC_SUPABASE_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
                --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" \
                --build-arg GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID \
                --build-arg GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET \
                --build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET \
                --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY \
                -t asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA} \
                -f Dockerfile \
                .

    - id: 'Push container image'
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'

    - id: 'Deploy to Cloud Run'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - '${_SERVICE_NAME}'
          - '--project=${_PROJECT_ID}'
          - '--region=${_REGION}'
          - '--image=asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
          - '--service-account=${_SERVICE_ACCOUNT}'
          - '--platform=managed'
          - '--vpc-connector=${_VPC_CONNECTOR}'
          - '--set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
          - '--ingress=all'
          - '--allow-unauthenticated'
          - '--quiet'

images:
    - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
