# Cloud Build pipeline for Creative Flow Studio (Next.js)
# References:
# - https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# - https://cloud.google.com/sql/docs/postgres/connect-run#terraform (Cloud SQL deploy flags)

options:
    logging: CLOUD_LOGGING_ONLY
    machineType: E2_HIGHCPU_8

tags:
    - creative-flow-studio
    - nextjs

substitutions:
    _REGION: asia-northeast1
    _PROJECT_ID: dataanalyticsclinic
    _REPO: creative-flow-studio
    _IMAGE_NAME: app
    _SERVICE_NAME: creative-flow-studio-dev
    _CLOUD_SQL_INSTANCE: dataanalyticsclinic:asia-northeast1:creative-flow-studio-sql
    _VPC_CONNECTOR: projects/dataanalyticsclinic/locations/asia-northeast1/connectors/dev-serverless-connector
    _SERVICE_ACCOUNT: cloud-run-runtime@dataanalyticsclinic.iam.gserviceaccount.com
    _NEXT_PUBLIC_APP_URL: 'SET_IN_TRIGGER'
    _NEXT_PUBLIC_SUPABASE_URL: 'SET_IN_TRIGGER'

serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/cloud-build-runner@dataanalyticsclinic.iam.gserviceaccount.com

availableSecrets:
    secretManager:
        # DATABASE_URL is included for migration step only, not for Next.js build
        - versionName: projects/${_PROJECT_ID}/secrets/database-url/versions/latest
          env: DATABASE_URL
        - versionName: projects/${_PROJECT_ID}/secrets/nextauth-secret/versions/latest
          env: NEXTAUTH_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-id/versions/latest
          env: GOOGLE_CLIENT_ID
        - versionName: projects/${_PROJECT_ID}/secrets/google-client-secret/versions/latest
          env: GOOGLE_CLIENT_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-service-role/versions/latest
          env: SUPABASE_SERVICE_ROLE_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-secret-key/versions/latest
          env: STRIPE_SECRET_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-webhook-secret/versions/latest
          env: STRIPE_WEBHOOK_SECRET
        - versionName: projects/${_PROJECT_ID}/secrets/gemini-api-key/versions/latest
          env: GEMINI_API_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/supabase-anon-key/versions/latest
          env: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - versionName: projects/${_PROJECT_ID}/secrets/stripe-publishable-key/versions/latest
          env: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

steps:
    - id: 'Install dependencies'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: bash
      args:
          - '-c'
          - |
              set -euo pipefail
              echo "Cloud Build Node version: $(node --version)"
              npm ci

    - id: 'Generate Prisma client'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npx
      args: ['prisma', 'generate']

    - id: 'Apply database migrations'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              set -euo pipefail
              
              # Cloud SQL Proxyをダウンロード
              echo "📥 Cloud SQL Proxyをダウンロードしています..."
              wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
              chmod +x cloud_sql_proxy
              
              # Cloud SQL Proxyをバックグラウンドで起動
              echo "🚀 Cloud SQL Proxyを起動しています..."
              ./cloud_sql_proxy -instances=${_CLOUD_SQL_INSTANCE}=tcp:5432 > /tmp/cloud-sql-proxy.log 2>&1 &
              PROXY_PID=$!
              
              # Proxyが起動するまで待機
              sleep 5
              
              # Proxyが正常に起動したか確認
              if ! ps -p $$PROXY_PID > /dev/null; then
                  echo "❌ Cloud SQL Proxyの起動に失敗しました"
                  cat /tmp/cloud-sql-proxy.log
                  exit 1
              fi
              
              echo "✅ Cloud SQL Proxyが起動しました (PID: $$PROXY_PID)"
              
              # DATABASE_URLを取得して、localhost経由に変換
              echo "🔑 データベース接続情報を取得しています..."
              DB_URL=$$DATABASE_URL
              echo "  元のDATABASE_URL: $$DB_URL"
              
              # Unix socket形式からTCP形式に変換
              # postgresql://user:pass@/db?host=/cloudsql/... -> postgresql://user:pass@127.0.0.1:5432/db
              DB_URL_LOCAL=$(echo "$$DB_URL" | sed 's|host=/cloudsql/[^?]*||' | sed 's|@/|@127.0.0.1:5432/|')
              echo "  変換後のDATABASE_URL: $$DB_URL_LOCAL"
              
              # データベース接続が確立されるまで待機（最大60秒）
              echo "⏳ データベース接続を待機しています..."
              export DATABASE_URL="$$DB_URL_LOCAL"
              MAX_RETRIES=60
              RETRY_COUNT=0
              CONNECTED=false
              
              while [ $$RETRY_COUNT -lt $$MAX_RETRIES ]; do
                  # Prisma migrate deployを試行して接続を確認
                  if npx prisma migrate deploy --skip-seed > /dev/null 2>&1; then
                      echo "✅ データベース接続が確立され、マイグレーションが完了しました"
                      CONNECTED=true
                      break
                  fi
                  # 接続エラーかどうかを確認（P1001エラーは接続エラー）
                  ERROR_OUTPUT=$(npx prisma migrate deploy --skip-seed 2>&1 || true)
                  if echo "$$ERROR_OUTPUT" | grep -q "P1001"; then
                      # 接続エラーの場合、リトライ
                      RETRY_COUNT=$$((RETRY_COUNT + 1))
                      if [ $$((RETRY_COUNT % 5)) -eq 0 ]; then
                          echo "  試行 $$RETRY_COUNT/$$MAX_RETRIES..."
                      fi
                      sleep 1
                  else
                      # 接続エラー以外の場合は成功とみなす（マイグレーションが既に適用済みなど）
                      echo "✅ データベース接続が確立されました"
                      CONNECTED=true
                      break
                  fi
              done
              
              if [ "$$CONNECTED" != "true" ]; then
                  echo "❌ データベース接続の確立に失敗しました（$$MAX_RETRIES回試行）"
                  echo "Cloud SQL Proxyログ:"
                  cat /tmp/cloud-sql-proxy.log
                  echo ""
                  echo "接続テスト:"
                  npx prisma migrate deploy --skip-seed || true
                  exit 1
              fi
              
              # 接続が確立されている場合、マイグレーションは既に実行済み
              if [ "$$CONNECTED" = "true" ]; then
                  echo "✅ マイグレーションは既に適用済みです"
              fi
              
              # Proxyを停止
              echo "🛑 Cloud SQL Proxyを停止しています..."
              kill $$PROXY_PID 2>/dev/null || true
              wait $$PROXY_PID 2>/dev/null || true
              
              echo "✅ マイグレーションが正常に完了しました"
      secretEnv:
          - DATABASE_URL
      waitFor: ['Generate Prisma client']

    - id: 'Build Next.js app'
      name: 'docker.io/library/node@sha256:202ae32103f362765c42bb8283fbec5167cb7c5687feca97ad6bfbf4af3df444'
      entrypoint: npm
      args: ['run', 'build']
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
          # NOTE: DATABASE_URL is NOT set during build - it's only set at runtime in Cloud Run
          # This prevents Next.js from hardcoding the DATABASE_URL during build
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - SUPABASE_SERVICE_ROLE_KEY
          - STRIPE_SECRET_KEY
          - STRIPE_WEBHOOK_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

    - id: 'Build container image'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      env:
          - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
          - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      secretEnv:
          - NEXTAUTH_SECRET
          - GOOGLE_CLIENT_ID
          - GOOGLE_CLIENT_SECRET
          - GEMINI_API_KEY
          - NEXT_PUBLIC_SUPABASE_ANON_KEY
          - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      args:
          - '-c'
          - |
              docker build \
                --build-arg NEXT_PUBLIC_APP_URL="${_NEXT_PUBLIC_APP_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_URL="${_NEXT_PUBLIC_SUPABASE_URL}" \
                --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
                --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" \
                --build-arg GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID \
                --build-arg GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET \
                --build-arg NEXTAUTH_SECRET=$$NEXTAUTH_SECRET \
                --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY \
                -t asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA} \
                -f Dockerfile \
                .

    - id: 'Push container image'
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'

    - id: 'Deploy to Cloud Run'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - '${_SERVICE_NAME}'
          - '--project=${_PROJECT_ID}'
          - '--region=${_REGION}'
          - '--image=asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
          - '--service-account=${_SERVICE_ACCOUNT}'
          - '--platform=managed'
          - '--vpc-connector=${_VPC_CONNECTOR}'
          - '--set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}'
          - '--ingress=all'
          - '--allow-unauthenticated'
          - '--quiet'

images:
    - 'asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
